services:
  web:
    image: plm_study_planner
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db:3306
      DB_USERNAME: root
      DB_PASSWORD: my_secret_pw
      DB_NAME: study_planner
    depends_on:
      - db
    volumes:
      - .:/var/www/html
      - ./node:/usr/src/app

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_pw
      MYSQL_DATABASE: study_planner
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
